version: '3.5'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

networks:
  kittens_exhibition:
    driver: bridge

services:

  db:
    image: postgres:13.10
    env_file:
      .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittens_exhibition

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      .env
    networks:
      - kittens_exhibition

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
#      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - /etc/nginx/conf.d/
      - static:/app/static/
      - backend_static:/backend_static/
      - backend_media:/backend_media/
    networks:
      - kittens_exhibition
