# Generated by Django 5.0.2 on 2024-10-03 22:37

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "Такая порода уже существует"},
                        max_length=50,
                        unique=True,
                        validators=[core.validators.name_validator],
                        verbose_name="Название породы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Порода",
                "verbose_name_plural": "Породы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Kitten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[core.validators.name_validator],
                        verbose_name="Имя котенка",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Слаг")),
                ("color", models.CharField(max_length=16)),
                ("birth_data", models.DateField()),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kittens",
                        to="kittens.breed",
                    ),
                ),
            ],
        ),
    ]
