# Generated by Django 5.0.2 on 2024-10-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kittens", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kitten",
            options={
                "ordering": ("name",),
                "verbose_name": "Котёнок",
                "verbose_name_plural": "Котята",
            },
        ),
    ]
